'use strict';
/**
 * AI Property Intelligence — SAMPLE DATA.
 *
 * Every number here (prices, absorption, pipelines, scores, scenario returns, project names) is
 * illustrative, written for the demo. Metro alignments come from the Living Score seed (itself
 * approximate); bridges, Ring Road 4, planning zones and district outlines are hand-drawn sketches.
 * Nothing in this file is official market or planning data.
 */

const DATA_UPDATED = '2026-09-25';
const PLANNING_HORIZONS = [2026, 2030, 2045];
/** Sample conversion rate used by the VND/USD switch (VND per USD). */
const VND_PER_USD = 25_400;

/** Sub-scores (0-100) shown on the district card. `risk` is "higher = riskier". */
const CRITERIA = [
  { key: 'planning', code: 'PL', label: 'Planning Potential', tone: 'planning', weight: 0.2 },
  { key: 'connectivity', code: 'MT', label: 'Connectivity', tone: 'mobility', weight: 0.15 },
  { key: 'infrastructure', code: 'IN', label: 'Infrastructure', tone: 'mobility', weight: 0.2 },
  { key: 'urban', code: 'UD', label: 'Urban Development', tone: 'planning', weight: 0.05 },
  { key: 'population', code: 'PG', label: 'Population Growth', tone: 'growth', weight: 0.05 },
  { key: 'demand', code: 'PD', label: 'Property Demand', tone: 'growth', weight: 0.15 },
  { key: 'pricePotential', code: 'PP', label: 'Price Potential', tone: 'growth', weight: 0.2 },
  { key: 'risk', code: 'RK', label: 'Investment Risk', tone: 'risk', weight: 0 },
];

/**
 * Districts. `center` + `radiusKm` build the illustrative outline (Voronoi cell clipped to a disc).
 * price: tr/m² (million VND per m²) for 2020 and now; yoy is the last-year change.
 * supplyDemand: k units for '24, '25, '26, '27F.
 * timeline: years are inclusive, 2025-2032 window; `planned` draws a dashed bar.
 */
const DISTRICTS = [
  {
    slug: 'gia-lam',
    name: 'Gia Lâm',
    tagline: 'East bank of the Red River · pop. 331k · 20 communes, 2 towns',
    center: [105.95, 21.04],
    radiusKm: 7.5,
    areaKm2: 116,
    scores: { planning: 92, connectivity: 86, infrastructure: 90, urban: 84, population: 81, demand: 88, pricePotential: 91, risk: 34 },
    scoreQ1: 83,
    aiConfidence: 0.82,
    price: { y2020: 32.3, now: 68.4, yoy: 0.142 },
    absorption: 87,
    absorptionDeltaQoQ: 9,
    pipeline: { units: 24_600, projects: 18 },
    rentalYield: 4.1,
    population: { y2020: 272, now: 331, y2030: 392 },
    density: 2850,
    supplyDemand: [
      { label: "'24", supply: 6.2, demand: 7.4 },
      { label: "'25", supply: 8.5, demand: 9.6 },
      { label: "'26", supply: 10.8, demand: 12.1 },
      { label: "'27F", supply: 14.6, demand: 12.4, forecast: true },
    ],
    infraImpacts: [
      { name: 'Metro Line 1', kind: 'metro', uplift: 18 },
      { name: 'Trần Hưng Đạo Bridge', kind: 'road', uplift: 13 },
      { name: 'Ring Road 4', kind: 'road', uplift: 9 },
      { name: 'Metro Line 4', kind: 'metro', uplift: 7, planned: true },
    ],
    timeline: [
      { name: 'Trần Hưng Đạo Br.', kind: 'road', start: 2025, end: 2027 },
      { name: 'Ring Road 4', kind: 'road', start: 2025, end: 2026 },
      { name: 'Urban district', kind: 'urban', start: 2026, end: 2027 },
      { name: 'Metro Line 1 · Gia Lâm section', kind: 'metro', start: 2026, end: 2031 },
      { name: 'Metro Line 4', kind: 'metro', start: 2028, end: 2032, planned: true },
    ],
    insight: {
      outlook: 'Positive',
      summary:
        'Yes, for buyers with a 5-year horizon. Growth is driven by committed transport projects rather than speculation, but entry timing and project selection matter.',
      drivers: 'Metro L1 + Ring Road 4, district-to-urban upgrade, east-bank CBD spillover',
      infrastructure: '3 bridges cut CBD commute to <20 min; est. +11–18% uplift within 1 km of stations',
      planning: '1,140 ha rezoned to mixed-use; TOD density bonus near Yên Viên Stn',
      demand: 'Young families moving over from Long Biên',
      risks: '24.6k-unit pipeline by 2028, bridge delays, flood exposure in low-lying communes',
      scenarios: {
        bear: { probability: 20, change: 12, note: 'Metro slips to 2032' },
        base: { probability: 55, change: 38, note: 'On-schedule infra' },
        bull: { probability: 25, change: 61, note: 'Urban district 2027' },
      },
      strategy:
        'Buy completed or near-handover stock within 800 m of Gia Lâm / Yên Viên stations. Avoid off-plan in outer communes until 2027 supply clears.',
    },
  },
  {
    slug: 'dong-anh',
    name: 'Đông Anh',
    tagline: 'North of the Red River · pop. 412k · airport corridor and new bridges',
    center: [105.845, 21.14],
    radiusKm: 9,
    areaKm2: 185,
    scores: { planning: 95, connectivity: 84, infrastructure: 92, urban: 86, population: 88, demand: 86, pricePotential: 93, risk: 41 },
    scoreQ1: 88,
    aiConfidence: 0.78,
    price: { y2020: 29.5, now: 66.2, yoy: 0.168 },
    absorption: 82,
    absorptionDeltaQoQ: 6,
    pipeline: { units: 31_200, projects: 22 },
    rentalYield: 3.8,
    population: { y2020: 382, now: 412, y2030: 505 },
    density: 2230,
    supplyDemand: [
      { label: "'24", supply: 7.8, demand: 8.1 },
      { label: "'25", supply: 10.2, demand: 10.9 },
      { label: "'26", supply: 12.9, demand: 13.4 },
      { label: "'27F", supply: 17.5, demand: 14.2, forecast: true },
    ],
    infraImpacts: [
      { name: 'Tứ Liên Bridge', kind: 'road', uplift: 16 },
      { name: 'Ring Road 4', kind: 'road', uplift: 11 },
      { name: 'Airport metro link', kind: 'metro', uplift: 9, planned: true },
      { name: 'Trần Hưng Đạo Bridge', kind: 'road', uplift: 4 },
    ],
    timeline: [
      { name: 'Tứ Liên Bridge', kind: 'road', start: 2025, end: 2028 },
      { name: 'Ring Road 4', kind: 'road', start: 2025, end: 2026 },
      { name: 'Urban district', kind: 'urban', start: 2025, end: 2026 },
      { name: 'Airport metro link', kind: 'metro', start: 2028, end: 2032, planned: true },
    ],
    insight: {
      outlook: 'Positive',
      summary:
        'Strong long-term story on the airport corridor and new river crossings, but supply is the heaviest in the city — returns depend on picking the right micro-location.',
      drivers: 'Urban-district upgrade, Tứ Liên Bridge, exhibition-centre and airport corridor',
      infrastructure: 'Tứ Liên Bridge puts Tây Hồ 10 min away; Ring Road 4 links the industrial belt',
      planning: 'Large mixed-use and smart-city zones along the Nhật Tân – Nội Bài axis',
      demand: 'Upgraders from the old core and airport-linked jobs',
      risks: '31k-unit pipeline, long build-out of new zones, speculative land plots',
      scenarios: {
        bear: { probability: 25, change: 8, note: 'Supply glut 2027-28' },
        base: { probability: 50, change: 34, note: 'Bridge opens 2028' },
        bull: { probability: 25, change: 58, note: 'Airport metro committed' },
      },
      strategy: 'Favour projects facing Tứ Liên Bridge approaches and the Nhật Tân axis; avoid land plots in outer communes without road access.',
    },
  },
  {
    slug: 'long-bien',
    name: 'Long Biên',
    tagline: 'First east-bank urban district · pop. 338k · Gia Lâm railway hub',
    center: [105.89, 21.045],
    radiusKm: 5,
    areaKm2: 60,
    scores: { planning: 88, connectivity: 92, infrastructure: 91, urban: 90, population: 80, demand: 90, pricePotential: 88, risk: 28 },
    scoreQ1: 87,
    aiConfidence: 0.84,
    price: { y2020: 41.8, now: 82.5, yoy: 0.118 },
    absorption: 89,
    absorptionDeltaQoQ: 4,
    pipeline: { units: 12_800, projects: 11 },
    rentalYield: 3.9,
    population: { y2020: 305, now: 338, y2030: 372 },
    density: 5630,
    supplyDemand: [
      { label: "'24", supply: 4.1, demand: 5.2 },
      { label: "'25", supply: 4.8, demand: 5.9 },
      { label: "'26", supply: 5.4, demand: 6.3 },
      { label: "'27F", supply: 6.1, demand: 6.6, forecast: true },
    ],
    infraImpacts: [
      { name: 'Metro Line 1', kind: 'metro', uplift: 15 },
      { name: 'Trần Hưng Đạo Bridge', kind: 'road', uplift: 12 },
      { name: 'Tứ Liên Bridge', kind: 'road', uplift: 5 },
      { name: 'Ring Road 4', kind: 'road', uplift: 3 },
    ],
    timeline: [
      { name: 'Trần Hưng Đạo Br.', kind: 'road', start: 2025, end: 2027 },
      { name: 'Metro Line 1', kind: 'metro', start: 2026, end: 2031 },
      { name: 'Gia Lâm rail hub TOD', kind: 'urban', start: 2027, end: 2030 },
    ],
    insight: {
      outlook: 'Positive',
      summary: 'The most mature east-bank market: lower risk and deep demand, with less upside left than Gia Lâm or Đông Anh.',
      drivers: 'Metro L1 at Gia Lâm Stn, established schools and malls, CBD spillover',
      infrastructure: 'Trần Hưng Đạo Bridge links straight into Hoàn Kiếm; rail hub redevelopment',
      planning: 'TOD redevelopment around the Gia Lâm railway yard',
      demand: 'Owner-occupiers and families',
      risks: 'High entry prices, limited new land, flood exposure near the dyke',
      scenarios: {
        bear: { probability: 20, change: 6, note: 'Rates stay high' },
        base: { probability: 60, change: 27, note: 'Bridge on schedule' },
        bull: { probability: 20, change: 41, note: 'Rail-yard TOD fast-tracked' },
      },
      strategy: 'Target resale stock near Gia Lâm Stn and the bridge landing; rental demand supports holding.',
    },
  },
  {
    slug: 'hoang-mai',
    name: 'Hoàng Mai',
    tagline: 'Southern gateway · pop. 540k · Line 1 and Ring Road 3 corridor',
    center: [105.855, 20.975],
    radiusKm: 4.5,
    areaKm2: 41,
    scores: { planning: 80, connectivity: 83, infrastructure: 82, urban: 78, population: 76, demand: 85, pricePotential: 80, risk: 38 },
    scoreQ1: 80,
    aiConfidence: 0.76,
    price: { y2020: 38.6, now: 69.9, yoy: 0.097 },
    absorption: 78,
    absorptionDeltaQoQ: 2,
    pipeline: { units: 15_400, projects: 14 },
    rentalYield: 4.4,
    population: { y2020: 506, now: 540, y2030: 575 },
    density: 13170,
    supplyDemand: [
      { label: "'24", supply: 5.6, demand: 5.9 },
      { label: "'25", supply: 6.4, demand: 6.2 },
      { label: "'26", supply: 7.1, demand: 6.9 },
      { label: "'27F", supply: 7.8, demand: 7.2, forecast: true },
    ],
    infraImpacts: [
      { name: 'Metro Line 1', kind: 'metro', uplift: 12 },
      { name: 'Ring Road 2.5', kind: 'road', uplift: 6 },
      { name: 'Yên Sở Park upgrade', kind: 'road', uplift: 4 },
    ],
    timeline: [
      { name: 'Ring Road 2.5', kind: 'road', start: 2025, end: 2027 },
      { name: 'Metro Line 1', kind: 'metro', start: 2026, end: 2031 },
      { name: 'Yên Sở Park', kind: 'urban', start: 2027, end: 2029 },
    ],
    insight: {
      outlook: 'Neutral',
      summary: 'Solid rental market with the best yields in the sample, but dense and congested — upside hinges on Metro Line 1.',
      drivers: 'Metro L1 stations, Ring Road 2.5 completion, Yên Sở Park',
      infrastructure: 'Line 1 would halve the commute to the core; Ring Road 3 already elevated',
      planning: 'Industrial-to-residential conversion along the Kim Ngưu corridor',
      demand: 'Renters and first-time buyers',
      risks: 'Traffic congestion, older stock, Line 1 timing',
      scenarios: {
        bear: { probability: 30, change: 5, note: 'Line 1 slips past 2033' },
        base: { probability: 50, change: 22, note: 'Line 1 on schedule' },
        bull: { probability: 20, change: 36, note: 'Park + conversions land' },
      },
      strategy: 'Buy for yield near future Line 1 stations; prefer projects with park frontage.',
    },
  },
  {
    slug: 'ha-dong',
    name: 'Hà Đông',
    tagline: 'South-west hub · pop. 420k · Line 2A terminus',
    center: [105.77, 20.96],
    radiusKm: 5,
    areaKm2: 48,
    scores: { planning: 78, connectivity: 86, infrastructure: 80, urban: 82, population: 84, demand: 82, pricePotential: 76, risk: 36 },
    scoreQ1: 79,
    aiConfidence: 0.8,
    price: { y2020: 36.2, now: 61.8, yoy: 0.083 },
    absorption: 76,
    absorptionDeltaQoQ: -2,
    pipeline: { units: 17_900, projects: 15 },
    rentalYield: 4.3,
    population: { y2020: 382, now: 420, y2030: 468 },
    density: 8750,
    supplyDemand: [
      { label: "'24", supply: 6.0, demand: 6.3 },
      { label: "'25", supply: 6.8, demand: 6.5 },
      { label: "'26", supply: 7.4, demand: 6.9 },
      { label: "'27F", supply: 8.1, demand: 7.0, forecast: true },
    ],
    infraImpacts: [
      { name: 'Metro Line 2A', kind: 'metro', uplift: 10 },
      { name: 'Ring Road 4', kind: 'road', uplift: 5 },
      { name: 'Hòa Lạc corridor', kind: 'road', uplift: 4, planned: true },
    ],
    timeline: [
      { name: 'Ring Road 4', kind: 'road', start: 2025, end: 2026 },
      { name: 'Hòa Lạc corridor', kind: 'road', start: 2027, end: 2032, planned: true },
    ],
    insight: {
      outlook: 'Neutral',
      summary: 'Already metro-served, so much of the uplift is priced in; a steady yield play rather than a growth play.',
      drivers: 'Operating Line 2A, Ring Road 4, western growth axis',
      infrastructure: 'Line 2A reaches Cát Linh in ~25 min; Ring Road 4 opens the west',
      planning: 'New urban zones towards Hòa Lạc',
      demand: 'Young professionals and families',
      risks: 'Large pipeline, oversupplied high-rise segment',
      scenarios: {
        bear: { probability: 30, change: 3, note: 'Pipeline overhang' },
        base: { probability: 50, change: 18, note: 'Steady demand' },
        bull: { probability: 20, change: 30, note: 'Hòa Lạc axis accelerates' },
      },
      strategy: 'Stay within walking distance of Line 2A stations; avoid new high-rise launches without amenities.',
    },
  },
  {
    slug: 'nam-tu-liem',
    name: 'Nam Từ Liêm',
    tagline: 'West-side office belt · pop. 290k · Line 3 corridor',
    center: [105.765, 21.013],
    radiusKm: 4.5,
    areaKm2: 32,
    scores: { planning: 84, connectivity: 90, infrastructure: 86, urban: 88, population: 83, demand: 87, pricePotential: 82, risk: 30 },
    scoreQ1: 83,
    aiConfidence: 0.83,
    price: { y2020: 46.5, now: 88.7, yoy: 0.106 },
    absorption: 84,
    absorptionDeltaQoQ: 3,
    pipeline: { units: 11_300, projects: 10 },
    rentalYield: 4.0,
    population: { y2020: 262, now: 290, y2030: 322 },
    density: 9060,
    supplyDemand: [
      { label: "'24", supply: 3.8, demand: 4.6 },
      { label: "'25", supply: 4.3, demand: 5.1 },
      { label: "'26", supply: 4.9, demand: 5.4 },
      { label: "'27F", supply: 5.2, demand: 5.6, forecast: true },
    ],
    infraImpacts: [
      { name: 'Metro Line 3', kind: 'metro', uplift: 12 },
      { name: 'Ring Road 3.5', kind: 'road', uplift: 6 },
      { name: 'Line 5 (Văn Cao – Hòa Lạc)', kind: 'metro', uplift: 5, planned: true },
    ],
    timeline: [
      { name: 'Line 3 underground', kind: 'metro', start: 2025, end: 2027 },
      { name: 'Ring Road 3.5', kind: 'road', start: 2026, end: 2029 },
      { name: 'Line 5', kind: 'metro', start: 2029, end: 2032, planned: true },
    ],
    insight: {
      outlook: 'Positive',
      summary: 'A proven office-and-apartment belt with Line 3 running; moderate upside with low risk.',
      drivers: 'Line 3, the national convention and sports cluster, office demand',
      infrastructure: 'Line 3 goes underground to Ga Hà Nội; Ring Road 3.5 adds a western bypass',
      planning: 'Mixed-use infill around Mỹ Đình and Tây Mỗ',
      demand: 'Expat and office tenants',
      risks: 'High entry prices, construction disruption on Line 3',
      scenarios: {
        bear: { probability: 20, change: 5, note: 'Office demand softens' },
        base: { probability: 60, change: 24, note: 'Line 3 fully open 2027' },
        bull: { probability: 20, change: 37, note: 'Line 5 committed' },
      },
      strategy: 'Buy near Line 3 stations for rental income; prefer completed stock with proven occupancy.',
    },
  },
  {
    slug: 'cau-giay',
    name: 'Cầu Giấy',
    tagline: 'Education and tech hub · pop. 296k · Line 3 terminus',
    center: [105.796, 21.0333],
    radiusKm: 3,
    areaKm2: 12,
    scores: { planning: 72, connectivity: 93, infrastructure: 88, urban: 94, population: 70, demand: 91, pricePotential: 74, risk: 22 },
    scoreQ1: 80,
    aiConfidence: 0.86,
    price: { y2020: 58.4, now: 104.6, yoy: 0.078 },
    absorption: 91,
    absorptionDeltaQoQ: 1,
    pipeline: { units: 3_900, projects: 5 },
    rentalYield: 3.7,
    population: { y2020: 283, now: 296, y2030: 304 },
    density: 24670,
    supplyDemand: [
      { label: "'24", supply: 1.4, demand: 2.3 },
      { label: "'25", supply: 1.2, demand: 2.4 },
      { label: "'26", supply: 1.3, demand: 2.5 },
      { label: "'27F", supply: 1.1, demand: 2.5, forecast: true },
    ],
    infraImpacts: [
      { name: 'Metro Line 3', kind: 'metro', uplift: 8 },
      { name: 'Metro Line 2 (planned)', kind: 'metro', uplift: 5, planned: true },
    ],
    timeline: [
      { name: 'Line 3 underground', kind: 'metro', start: 2025, end: 2027 },
      { name: 'Metro Line 2', kind: 'metro', start: 2029, end: 2032, planned: true },
    ],
    insight: {
      outlook: 'Neutral',
      summary: 'Scarce supply keeps prices firm, but it is built out — expect steady rather than outsized gains.',
      drivers: 'Universities, tech offices, Line 3 terminus',
      infrastructure: 'Line 3 already operating; Line 2 would add a north–south link',
      planning: 'Little new land; growth comes from redevelopment',
      demand: 'Students, young professionals, investors',
      risks: 'Very high entry price, low yield, ageing mid-rise stock',
      scenarios: {
        bear: { probability: 20, change: 4, note: 'Price ceiling reached' },
        base: { probability: 60, change: 16, note: 'Scarcity premium holds' },
        bull: { probability: 20, change: 25, note: 'Redevelopment wave' },
      },
      strategy: 'Hold for capital preservation; buy small units near universities for rental.',
    },
  },
  {
    slug: 'tay-ho',
    name: 'Tây Hồ',
    tagline: 'West Lake · pop. 168k · premium and expat market',
    center: [105.823, 21.07],
    radiusKm: 3.5,
    areaKm2: 24,
    scores: { planning: 76, connectivity: 78, infrastructure: 80, urban: 86, population: 66, demand: 84, pricePotential: 79, risk: 26 },
    scoreQ1: 78,
    aiConfidence: 0.81,
    price: { y2020: 62.1, now: 112.8, yoy: 0.091 },
    absorption: 80,
    absorptionDeltaQoQ: 0,
    pipeline: { units: 4_700, projects: 6 },
    rentalYield: 3.4,
    population: { y2020: 160, now: 168, y2030: 176 },
    density: 7000,
    supplyDemand: [
      { label: "'24", supply: 1.6, demand: 1.9 },
      { label: "'25", supply: 1.8, demand: 2.0 },
      { label: "'26", supply: 1.9, demand: 2.1 },
      { label: "'27F", supply: 2.2, demand: 2.1, forecast: true },
    ],
    infraImpacts: [
      { name: 'Tứ Liên Bridge', kind: 'road', uplift: 9 },
      { name: 'Metro Line 2 (planned)', kind: 'metro', uplift: 6, planned: true },
    ],
    timeline: [
      { name: 'Tứ Liên Bridge', kind: 'road', start: 2025, end: 2028 },
      { name: 'Metro Line 2', kind: 'metro', start: 2029, end: 2032, planned: true },
    ],
    insight: {
      outlook: 'Neutral',
      summary: 'Premium lifestyle market with durable demand; gains track the Tứ Liên Bridge and lakefront projects.',
      drivers: 'West Lake frontage, expat demand, Tứ Liên Bridge',
      infrastructure: 'Tứ Liên Bridge links to Đông Anh; Line 2 planned along the lake',
      planning: 'Height limits around the lake keep supply tight',
      demand: 'Expats and high-net-worth buyers',
      risks: 'Lowest yield in the sample, sensitive to expat demand',
      scenarios: {
        bear: { probability: 25, change: 2, note: 'Expat demand dips' },
        base: { probability: 55, change: 17, note: 'Steady premium' },
        bull: { probability: 20, change: 28, note: 'Bridge + Line 2 together' },
      },
      strategy: 'Buy lake-view or bridge-adjacent stock for long holds; rent furnished to expats.',
    },
  },
  {
    slug: 'dong-da',
    name: 'Đống Đa',
    tagline: 'Historic core · pop. 372k · Line 2A and Line 3 interchange',
    center: [105.8285, 21.0175],
    radiusKm: 2.5,
    areaKm2: 10,
    scores: { planning: 62, connectivity: 90, infrastructure: 84, urban: 80, population: 58, demand: 86, pricePotential: 66, risk: 30 },
    scoreQ1: 74,
    aiConfidence: 0.79,
    price: { y2020: 70.5, now: 118.4, yoy: 0.064 },
    absorption: 83,
    absorptionDeltaQoQ: -1,
    pipeline: { units: 2_100, projects: 3 },
    rentalYield: 3.5,
    population: { y2020: 376, now: 372, y2030: 360 },
    density: 37200,
    supplyDemand: [
      { label: "'24", supply: 0.7, demand: 1.2 },
      { label: "'25", supply: 0.6, demand: 1.1 },
      { label: "'26", supply: 0.8, demand: 1.2 },
      { label: "'27F", supply: 0.7, demand: 1.2, forecast: true },
    ],
    infraImpacts: [
      { name: 'Metro Line 3', kind: 'metro', uplift: 6 },
      { name: 'Metro Line 2A', kind: 'metro', uplift: 4 },
    ],
    timeline: [
      { name: 'Line 3 underground', kind: 'metro', start: 2025, end: 2027 },
      { name: 'Old-quarter decongestion', kind: 'urban', start: 2027, end: 2032, planned: true },
    ],
    insight: {
      outlook: 'Cautious',
      summary: 'Central and well connected, but the city plans to move population out of the core — limited upside.',
      drivers: 'Two metro lines, hospitals and universities',
      infrastructure: 'Line 2A and Line 3 interchange at Cát Linh',
      planning: 'Decongestion policy caps new residential density',
      demand: 'Owner-occupiers and small investors',
      risks: 'Shrinking population, old collective-housing stock, tight lanes',
      scenarios: {
        bear: { probability: 30, change: -2, note: 'Decongestion bites' },
        base: { probability: 50, change: 12, note: 'Stable core demand' },
        bull: { probability: 20, change: 20, note: 'Old-block redevelopment' },
      },
      strategy: 'Only buy near metro interchanges; favour collective-housing blocks slated for redevelopment.',
    },
  },
  {
    slug: 'hoan-kiem',
    name: 'Hoàn Kiếm',
    tagline: 'Old Quarter and CBD · pop. 135k · heritage limits',
    center: [105.8542, 21.0285],
    radiusKm: 2,
    areaKm2: 5,
    scores: { planning: 52, connectivity: 88, infrastructure: 82, urban: 76, population: 42, demand: 80, pricePotential: 60, risk: 32 },
    scoreQ1: 70,
    aiConfidence: 0.74,
    price: { y2020: 115.0, now: 178.5, yoy: 0.052 },
    absorption: 72,
    absorptionDeltaQoQ: -3,
    pipeline: { units: 400, projects: 1 },
    rentalYield: 3.1,
    population: { y2020: 141, now: 135, y2030: 118 },
    density: 27000,
    supplyDemand: [
      { label: "'24", supply: 0.1, demand: 0.2 },
      { label: "'25", supply: 0.2, demand: 0.2 },
      { label: "'26", supply: 0.1, demand: 0.2 },
      { label: "'27F", supply: 0.1, demand: 0.2, forecast: true },
    ],
    infraImpacts: [
      { name: 'Metro Line 3 (Ga Hà Nội)', kind: 'metro', uplift: 5 },
      { name: 'Trần Hưng Đạo Bridge', kind: 'road', uplift: 3 },
    ],
    timeline: [
      { name: 'Line 3 to Ga Hà Nội', kind: 'metro', start: 2025, end: 2027 },
      { name: 'Trần Hưng Đạo Br.', kind: 'road', start: 2025, end: 2027 },
      { name: 'Old Quarter relocation', kind: 'urban', start: 2026, end: 2032, planned: true },
    ],
    insight: {
      outlook: 'Cautious',
      summary: 'Trophy location with the highest prices, but residential supply is shrinking by policy — better for commercial than residential plays.',
      drivers: 'Tourism, CBD offices, heritage appeal',
      infrastructure: 'Line 3 reaches Ga Hà Nội; Trần Hưng Đạo Bridge lands here',
      planning: 'Old Quarter population relocation, strict heritage height limits',
      demand: 'Commercial tenants and trophy buyers',
      risks: 'Policy-driven population decline, very low yield',
      scenarios: {
        bear: { probability: 30, change: -4, note: 'Relocation accelerates' },
        base: { probability: 50, change: 9, note: 'Commercial demand holds' },
        bull: { probability: 20, change: 16, note: 'Tourism boom' },
      },
      strategy: 'Prefer street-front commercial units over apartments; residential upside is limited.',
    },
  },
];

/** Metro lines drawn on the map, from the Living Score seed. `opens` decides solid vs planned per horizon. */
const METRO_LINES = [
  { id: 'L2A', seed: 'Tuyến 2A', name: 'Line 2A Cát Linh – Hà Đông', color: '#7FDDF0', opens: 2021 },
  { id: 'L3', seed: 'Tuyến 3 Nhổn', name: 'Line 3 Nhổn – Cầu Giấy', color: '#3CC8E8', opens: 2024 },
  { id: 'L3', seed: 'Tuyến 3 Cầu Giấy', name: 'Line 3 Cầu Giấy – Ga Hà Nội', color: '#3CC8E8', opens: 2027 },
  { id: 'L1', seed: 'Tuyến 1 Yên', name: 'Line 1 Yên Viên – Ngọc Hồi', color: '#3CC8E8', opens: 2031 },
  { id: 'L2', seed: 'Tuyến 2 Nam', name: 'Line 2 Nam Thăng Long – Trần Hưng Đạo', color: '#3CC8E8', opens: 2035 },
];

/** Stations used for TOD circles and project proximity (subset; coordinates from the seed alignments). */
const STATIONS = [
  { slug: 'yen-vien', name: 'Yên Viên Stn', line: 'L1', coords: [105.935, 21.076], opens: 2031, tod: true },
  { slug: 'gia-lam', name: 'Gia Lâm Stn', line: 'L1', coords: [105.885, 21.048], opens: 2031, tod: true },
  { slug: 'long-bien', name: 'Long Biên Stn', line: 'L1', coords: [105.86, 21.033], opens: 2031, tod: false },
  { slug: 'ga-ha-noi', name: 'Ga Hà Nội', line: 'L3', coords: [105.8412, 21.0245], opens: 2027, tod: true },
  { slug: 'giap-bat', name: 'Giáp Bát Stn', line: 'L1', coords: [105.842, 20.975], opens: 2031, tod: true },
  { slug: 'cau-giay', name: 'Cầu Giấy Stn', line: 'L3', coords: [105.7985, 21.0333], opens: 2024, tod: true },
  { slug: 'cat-linh', name: 'Cát Linh Stn', line: 'L2A', coords: [105.8265, 21.0289], opens: 2021, tod: true },
  { slug: 'ha-dong', name: 'Hà Đông Stn', line: 'L2A', coords: [105.7745, 20.9694], opens: 2021, tod: true },
  { slug: 'cau-dien', name: 'Cầu Diễn Stn', line: 'L3', coords: [105.7635, 21.0368], opens: 2024, tod: false },
  { slug: 'nam-thang-long', name: 'Nam Thăng Long Stn', line: 'L2', coords: [105.7885, 21.079], opens: 2035, tod: true },
];

/** Major road / bridge projects (hand-drawn sketches). */
const INFRASTRUCTURE = [
  { slug: 'tran-hung-dao-bridge', name: 'Trần Hưng Đạo Bridge', opens: 2027, coords: [[105.8575, 21.0205], [105.868, 21.0215], [105.879, 21.023]] },
  { slug: 'tu-lien-bridge', name: 'Tứ Liên Bridge', opens: 2028, coords: [[105.838, 21.075], [105.849, 21.083], [105.86, 21.092]] },
  {
    slug: 'ring-road-4',
    name: 'Ring Road 4',
    opens: 2026,
    coords: [[105.74, 21.2], [105.83, 21.21], [105.93, 21.15], [105.99, 21.06], [105.98, 20.96], [105.9, 20.88], [105.76, 20.87], [105.69, 20.95]],
  },
  { slug: 'ring-road-2-5', name: 'Ring Road 2.5', opens: 2027, coords: [[105.815, 20.99], [105.84, 20.985], [105.868, 20.988]] },
];

/** Planning zones (filled) and large urban developments (outlined). Rectangles: centre + size in km. */
const PLANNING_ZONES = [
  { slug: 'gl-mixed-use', district: 'gia-lam', kind: 'zone', name: 'Gia Lâm mixed-use rezoning · 1,140 ha', center: [105.955, 21.03], sizeKm: [3.2, 2.4], from: 2026 },
  { slug: 'gl-yen-vien-tod', district: 'gia-lam', kind: 'zone', name: 'Yên Viên TOD density bonus', center: [105.938, 21.07], sizeKm: [1.4, 1.1], from: 2030 },
  { slug: 'gl-east-gate', district: 'gia-lam', kind: 'development', name: 'East Gate urban area', center: [105.975, 21.005], sizeKm: [2.0, 1.6], from: 2026 },
  { slug: 'gl-river-city', district: 'gia-lam', kind: 'development', name: 'Riverside new town', center: [105.92, 21.0], sizeKm: [1.8, 1.4], from: 2030 },
  { slug: 'da-smart-city', district: 'dong-anh', kind: 'zone', name: 'North smart-city zone', center: [105.8, 21.1], sizeKm: [4.0, 3.0], from: 2026 },
  { slug: 'da-exhibition', district: 'dong-anh', kind: 'development', name: 'Exhibition-centre district', center: [105.87, 21.12], sizeKm: [2.4, 2.0], from: 2026 },
  { slug: 'da-airport-axis', district: 'dong-anh', kind: 'zone', name: 'Airport-axis logistics & housing', center: [105.83, 21.18], sizeKm: [3.0, 2.2], from: 2045 },
  { slug: 'lb-rail-yard', district: 'long-bien', kind: 'zone', name: 'Gia Lâm rail-yard TOD', center: [105.888, 21.043], sizeKm: [1.2, 0.9], from: 2030 },
  { slug: 'hm-kim-nguu', district: 'hoang-mai', kind: 'zone', name: 'Kim Ngưu conversion corridor', center: [105.862, 20.99], sizeKm: [1.6, 1.0], from: 2030 },
  { slug: 'hd-west-axis', district: 'ha-dong', kind: 'development', name: 'Western axis new town', center: [105.735, 20.955], sizeKm: [2.4, 1.8], from: 2030 },
  { slug: 'ntl-tay-mo', district: 'nam-tu-liem', kind: 'development', name: 'Tây Mỗ mixed-use', center: [105.745, 21.005], sizeKm: [2.0, 1.4], from: 2026 },
];

const GREEN_SPACES = [
  { name: 'Riverside Park', center: [105.915, 21.022], sizeKm: [1.2, 0.8] },
  { name: 'Yên Sở Park', center: [105.86, 20.965], sizeKm: [1.8, 1.2] },
  { name: 'West Lake', center: [105.822, 21.058], sizeKm: [2.6, 2.2] },
  { name: 'Thống Nhất Park', center: [105.843, 21.015], sizeKm: [0.6, 0.5] },
  { name: 'Hòa Bình Park', center: [105.785, 21.065], sizeKm: [0.9, 0.7] },
];

/**
 * Property projects. `price5y` is the tr/m² five years ago (Q3 2021); the quarterly history is
 * interpolated between it and `pricePerM2`. `pois` are the landmarks drawn on the deep-dive map;
 * projects without them get generic nearby landmarks generated from their location.
 */
const PROJECTS = [
  {
    slug: 'riverside-aurora',
    name: 'Riverside Aurora',
    tower: 'Tower B2',
    district: 'gia-lam',
    ward: 'Yên Viên',
    coords: [105.9377, 21.0734],
    floors: 34,
    units: 612,
    typical: { beds: 2, m2: 74 },
    handover: 'Q2 2027',
    pricePerM2: 72.8,
    price5y: 44.6,
    soldPct: 76,
    devScore: 87,
    devNote: 'top 8% district',
    riskScore: 28,
    riskNote: 'low · supply watch',
    milestone: { quarter: 14, label: 'L1 approved' },
    pois: [
      { kind: 'school', name: 'Intl. School', coords: [105.9412, 21.0751] },
      { kind: 'school', name: 'Yên Viên Primary', coords: [105.9335, 21.0702] },
      { kind: 'hospital', name: 'General Hospital', coords: [105.9478, 21.0655] },
      { kind: 'mall', name: 'Regional mall · 2027', coords: [105.9311, 21.0671] },
      { kind: 'park', name: 'Riverside Park · 14 ha', coords: [105.9335, 21.0786] },
    ],
    plannedInfra: [
      { name: 'Metro Line 1 · Gia Lâm section', kind: 'metro', year: 2031 },
      { name: 'Trần Hưng Đạo Bridge', kind: 'road', year: 2027 },
      { name: 'Ring Road 4 interchange', kind: 'road', year: 2027 },
    ],
    aiTake:
      "Priced 6% above district, justified by station proximity. Base case 5Y value 7.1–7.6 tỷ. Main risk: East Gate's unsold stock may cap resale prices through 2028.",
  },
  {
    slug: 'lotus-park',
    name: 'Lotus Park',
    tower: 'Phase 1',
    district: 'gia-lam',
    ward: 'Yên Viên',
    coords: [105.9462, 21.0797],
    floors: 28,
    units: 480,
    typical: { beds: 2, m2: 70 },
    handover: 'Q4 2027',
    pricePerM2: 69.5,
    price5y: 43.1,
    soldPct: 91,
    devScore: 84,
    devNote: 'top 15% district',
    riskScore: 26,
    riskNote: 'low · well sold',
    milestone: { quarter: 8, label: 'L1 approved' },
    plannedInfra: [
      { name: 'Metro Line 1 · Gia Lâm section', kind: 'metro', year: 2031 },
      { name: 'Ring Road 4 interchange', kind: 'road', year: 2027 },
    ],
    aiTake: 'Nearly sold out at a small discount to Riverside Aurora; resale units should track the district as Line 1 approaches.',
  },
  {
    slug: 'east-gate-residences',
    name: 'East Gate Residences',
    tower: 'Block A',
    district: 'gia-lam',
    ward: 'Trâu Quỳ',
    coords: [105.9705, 21.0085],
    floors: 30,
    units: 1_240,
    typical: { beds: 2, m2: 68 },
    handover: 'Q1 2028',
    pricePerM2: 64.1,
    price5y: 40.2,
    soldPct: 58,
    devScore: 74,
    devNote: 'mid-pack district',
    riskScore: 52,
    riskNote: 'medium · slow sales',
    milestone: { quarter: 11, label: 'Launch' },
    plannedInfra: [
      { name: 'Ring Road 4', kind: 'road', year: 2026 },
      { name: 'Metro Line 4 (planned)', kind: 'metro', year: 2032 },
    ],
    aiTake: 'Cheapest entry in the east cluster, but 42% unsold and 3 km from the nearest station — wait for handover discounts.',
  },
  {
    slug: 'trau-quy-garden',
    name: 'Trâu Quỳ Garden',
    tower: 'Garden Villas',
    district: 'gia-lam',
    ward: 'Trâu Quỳ',
    coords: [105.9362, 21.0135],
    floors: 21,
    units: 360,
    typical: { beds: 3, m2: 92 },
    handover: 'Completed 2025',
    pricePerM2: 61.8,
    price5y: 37.9,
    soldPct: 84,
    devScore: 79,
    devNote: 'top 30% district',
    riskScore: 31,
    riskNote: 'low · completed',
    milestone: { quarter: 16, label: 'Handover' },
    plannedInfra: [
      { name: 'Trần Hưng Đạo Bridge', kind: 'road', year: 2027 },
      { name: 'Ring Road 4', kind: 'road', year: 2026 },
    ],
    aiTake: 'Completed stock near the university cluster; good for rental now, with bridge-driven upside from 2027.',
  },
  {
    slug: 'river-crest',
    name: 'River Crest',
    tower: 'Tower C',
    district: 'long-bien',
    ward: 'Ngọc Lâm',
    coords: [105.8818, 21.0443],
    floors: 38,
    units: 720,
    typical: { beds: 2, m2: 76 },
    handover: 'Q3 2026',
    pricePerM2: 86.4,
    price5y: 52.8,
    soldPct: 88,
    devScore: 86,
    devNote: 'top 10% district',
    riskScore: 24,
    riskNote: 'low · handover now',
    milestone: { quarter: 12, label: 'Bridge approved' },
    plannedInfra: [
      { name: 'Metro Line 1 · Gia Lâm Stn', kind: 'metro', year: 2031 },
      { name: 'Trần Hưng Đạo Bridge', kind: 'road', year: 2027 },
    ],
    aiTake: 'Walking distance to Gia Lâm Stn and the bridge landing; priced for it, so returns come mainly from rent.',
  },
  {
    slug: 'north-link-city',
    name: 'North Link City',
    tower: 'Zone S1',
    district: 'dong-anh',
    ward: 'Vĩnh Ngọc',
    coords: [105.8445, 21.0915],
    floors: 32,
    units: 1_560,
    typical: { beds: 2, m2: 72 },
    handover: 'Q4 2028',
    pricePerM2: 68.9,
    price5y: 35.4,
    soldPct: 64,
    devScore: 85,
    devNote: 'top 12% district',
    riskScore: 45,
    riskNote: 'medium · off-plan',
    milestone: { quarter: 10, label: 'Tứ Liên approved' },
    plannedInfra: [
      { name: 'Tứ Liên Bridge', kind: 'road', year: 2028 },
      { name: 'Ring Road 4', kind: 'road', year: 2026 },
    ],
    aiTake: 'Direct beneficiary of Tứ Liên Bridge; off-plan risk is real, so stage payments to the bridge timeline.',
  },
  {
    slug: 'southgate-park',
    name: 'Southgate Park',
    tower: 'Tower 1',
    district: 'hoang-mai',
    ward: 'Giáp Bát',
    coords: [105.8452, 20.9788],
    floors: 29,
    units: 540,
    typical: { beds: 2, m2: 69 },
    handover: 'Q2 2027',
    pricePerM2: 71.2,
    price5y: 48.9,
    soldPct: 79,
    devScore: 78,
    devNote: 'top 25% district',
    riskScore: 36,
    riskNote: 'medium · Line 1 timing',
    milestone: { quarter: 8, label: 'L1 approved' },
    plannedInfra: [
      { name: 'Metro Line 1 · Giáp Bát Stn', kind: 'metro', year: 2031 },
      { name: 'Ring Road 2.5', kind: 'road', year: 2027 },
    ],
    aiTake: 'Yield play beside the future Giáp Bát station; expect ~4.5% gross rent while Line 1 is built.',
  },
  {
    slug: 'west-line-residences',
    name: 'West Line Residences',
    tower: 'Tower A',
    district: 'ha-dong',
    ward: 'Văn Quán',
    coords: [105.7917, 20.9812],
    floors: 35,
    units: 820,
    typical: { beds: 2, m2: 71 },
    handover: 'Completed 2024',
    pricePerM2: 63.4,
    price5y: 45.1,
    soldPct: 93,
    devScore: 76,
    devNote: 'top 30% district',
    riskScore: 29,
    riskNote: 'low · completed',
    milestone: { quarter: 12, label: 'Handover' },
    plannedInfra: [{ name: 'Ring Road 4', kind: 'road', year: 2026 }],
    aiTake: 'Metro-served and fully let; a defensive holding with modest upside.',
  },
  {
    slug: 'metro-one-residences',
    name: 'Metro One Residences',
    tower: 'Tower M1',
    district: 'nam-tu-liem',
    ward: 'Phú Diễn',
    coords: [105.7602, 21.0385],
    floors: 36,
    units: 690,
    typical: { beds: 2, m2: 73 },
    handover: 'Q1 2027',
    pricePerM2: 91.6,
    price5y: 57.3,
    soldPct: 86,
    devScore: 83,
    devNote: 'top 15% district',
    riskScore: 27,
    riskNote: 'low · metro-served',
    milestone: { quarter: 12, label: 'L3 opened' },
    plannedInfra: [
      { name: 'Ring Road 3.5', kind: 'road', year: 2029 },
      { name: 'Line 5 (planned)', kind: 'metro', year: 2032 },
    ],
    aiTake: 'Next to Cầu Diễn station on Line 3; the premium is deserved, upside depends on Line 5.',
  },
  {
    slug: 'lakeside-one',
    name: 'Lakeside One',
    tower: 'West Tower',
    district: 'tay-ho',
    ward: 'Phú Thượng',
    coords: [105.8165, 21.0812],
    floors: 27,
    units: 310,
    typical: { beds: 3, m2: 110 },
    handover: 'Q4 2026',
    pricePerM2: 121.5,
    price5y: 78.2,
    soldPct: 82,
    devScore: 81,
    devNote: 'top 20% district',
    riskScore: 25,
    riskNote: 'low · premium',
    milestone: { quarter: 10, label: 'Tứ Liên approved' },
    plannedInfra: [
      { name: 'Tứ Liên Bridge', kind: 'road', year: 2028 },
      { name: 'Metro Line 2 (planned)', kind: 'metro', year: 2035 },
    ],
    aiTake: 'Scarce lake-view stock; hold for capital preservation and furnished expat rentals.',
  },
];

module.exports = {
  DATA_UPDATED,
  PLANNING_HORIZONS,
  VND_PER_USD,
  CRITERIA,
  DISTRICTS,
  METRO_LINES,
  STATIONS,
  INFRASTRUCTURE,
  PLANNING_ZONES,
  GREEN_SPACES,
  PROJECTS,
};
