'use strict';
/**
 * ⚠ DEMO / ESTIMATED DATA ⚠
 * Every number in this file (population, income, rent, competitor counts, foot traffic...) is
 * illustrative demo data for the Hanoi Business Copilot MVP. It is NOT official market data and
 * must never be presented as such — the API and UI both label it "Demo / Estimated Data".
 */

/** The 6 business types the Copilot can analyse. */
const CATEGORIES = [
  {
    key: 'coffee-shop',
    name: 'Coffee shop',
    nameVi: 'Quán cà phê',
    icon: 'coffee',
    avgSizeM2: 61,
    avgTicketVnd: 45_000,
    dailyCustomersAtFull: 220,
    setupCostPerM2Vnd: 5_400_000,
    costModel: { cogsRatio: 0.3, staffFte: 4, staffSalaryVnd: 9_000_000, utilitiesPerM2Vnd: 115_000, marketingPct: 0.023, otherPct: 0.02 },
    traffic: 'morning',
    // How much each base attribute drives demand for this category (sums do not need to hit 1).
    demandWeights: { officeWorkers: 0.26, students: 0.16, footTraffic: 0.18, income: 0.12, population: 0.12, visitors: 0.16 },
    competitionSubtypes: [
      { key: 'chain_cafes', label: 'Chain cafés' },
      { key: 'specialty_coffee', label: 'Specialty coffee' },
      { key: 'local_cafe', label: 'Local cà phê' },
      { key: 'takeaway_kiosks', label: 'Takeaway kiosks' },
    ],
  },
  {
    key: 'restaurant',
    name: 'Restaurant',
    nameVi: 'Nhà hàng',
    icon: 'utensils',
    avgSizeM2: 110,
    avgTicketVnd: 120_000,
    dailyCustomersAtFull: 150,
    setupCostPerM2Vnd: 4_800_000,
    costModel: { cogsRatio: 0.34, staffFte: 8, staffSalaryVnd: 8_500_000, utilitiesPerM2Vnd: 140_000, marketingPct: 0.03, otherPct: 0.025 },
    traffic: 'meals',
    demandWeights: { population: 0.24, income: 0.2, footTraffic: 0.18, officeWorkers: 0.14, students: 0.06, visitors: 0.18 },
    competitionSubtypes: [
      { key: 'fine_dining', label: 'Fine dining' },
      { key: 'casual_dining', label: 'Casual dining' },
      { key: 'street_food', label: 'Street food' },
      { key: 'fast_food', label: 'Fast food chains' },
    ],
  },
  {
    key: 'retail-store',
    name: 'Retail store',
    nameVi: 'Cửa hàng bán lẻ',
    icon: 'bag',
    avgSizeM2: 80,
    avgTicketVnd: 350_000,
    dailyCustomersAtFull: 45,
    setupCostPerM2Vnd: 3_800_000,
    costModel: { cogsRatio: 0.52, staffFte: 3, staffSalaryVnd: 8_000_000, utilitiesPerM2Vnd: 80_000, marketingPct: 0.035, otherPct: 0.02 },
    traffic: 'afternoon',
    demandWeights: { footTraffic: 0.26, income: 0.22, population: 0.2, officeWorkers: 0.1, students: 0.06, visitors: 0.16 },
    competitionSubtypes: [
      { key: 'mall_anchor', label: 'Trung tâm thương mại' },
      { key: 'boutique', label: 'Boutique độc lập' },
      { key: 'street_shop', label: 'Cửa hàng mặt phố' },
      { key: 'online_pickup', label: 'Điểm nhận hàng online' },
    ],
  },
  {
    key: 'gym',
    name: 'Gym',
    nameVi: 'Phòng gym',
    icon: 'dumbbell',
    avgSizeM2: 200,
    // Per-visit equivalent of a ~600k/month membership; large gyms rent cheaper upper floors.
    avgTicketVnd: 40_000,
    dailyCustomersAtFull: 260,
    rentFactor: 0.45,
    setupCostPerM2Vnd: 2_600_000,
    costModel: { cogsRatio: 0.08, staffFte: 6, staffSalaryVnd: 10_000_000, utilitiesPerM2Vnd: 95_000, marketingPct: 0.05, otherPct: 0.03 },
    traffic: 'bimodal',
    demandWeights: { population: 0.34, income: 0.3, officeWorkers: 0.18, footTraffic: 0.08, students: 0.08, visitors: 0.02 },
    competitionSubtypes: [
      { key: 'chain_gym', label: 'Chuỗi phòng gym' },
      { key: 'boutique_studio', label: 'Studio boutique' },
      { key: 'yoga_pilates', label: 'Yoga / Pilates' },
      { key: 'crossfit_box', label: 'CrossFit box' },
    ],
  },
  {
    key: 'pharmacy',
    name: 'Pharmacy',
    nameVi: 'Nhà thuốc',
    icon: 'pill',
    avgSizeM2: 40,
    avgTicketVnd: 120_000,
    dailyCustomersAtFull: 80,
    setupCostPerM2Vnd: 6_500_000,
    costModel: { cogsRatio: 0.62, staffFte: 3, staffSalaryVnd: 9_500_000, utilitiesPerM2Vnd: 90_000, marketingPct: 0.015, otherPct: 0.02 },
    traffic: 'evening',
    demandWeights: { population: 0.4, footTraffic: 0.2, income: 0.14, officeWorkers: 0.12, students: 0.1, visitors: 0.04 },
    competitionSubtypes: [
      { key: 'chain_pharmacy', label: 'Chuỗi nhà thuốc' },
      { key: 'independent_pharmacy', label: 'Nhà thuốc độc lập' },
      { key: 'hospital_pharmacy', label: 'Nhà thuốc bệnh viện' },
      { key: 'online_pharmacy', label: 'Nhà thuốc online' },
    ],
  },
  {
    key: 'convenience-store',
    name: 'Convenience store',
    nameVi: 'Cửa hàng tiện lợi',
    icon: 'store',
    avgSizeM2: 60,
    avgTicketVnd: 60_000,
    dailyCustomersAtFull: 260,
    setupCostPerM2Vnd: 4_400_000,
    costModel: { cogsRatio: 0.66, staffFte: 5, staffSalaryVnd: 7_500_000, utilitiesPerM2Vnd: 130_000, marketingPct: 0.012, otherPct: 0.02 },
    traffic: 'broad',
    demandWeights: { population: 0.28, footTraffic: 0.24, officeWorkers: 0.16, students: 0.12, income: 0.08, visitors: 0.12 },
    competitionSubtypes: [
      { key: 'chain_conv', label: 'Chuỗi tiện lợi (24h)' },
      { key: 'mini_supermarket', label: 'Siêu thị mini' },
      { key: 'local_grocery', label: 'Tạp hoá truyền thống' },
      { key: 'vending', label: 'Máy bán hàng tự động' },
    ],
  },
];

/**
 * Base, category-independent attributes per district. Coordinates are approximate district
 * centroids; `population`/`incomeIndex`/etc. are demo estimates for the MVP, not census data.
 */
const LOCATIONS = [
  {
    slug: 'cau-giay',
    name: 'Cầu Giấy',
    cluster: 'Duy Tân – Trần Thái Tông office cluster',
    center: [105.796, 21.0333],
    population: 292_000,
    incomeIndex: 74,
    officeWorkersK: 62,
    studentsK: 48,
    footTrafficIndex: 90,
    metroAccessibility: 88,
    metroLines: 1,
    schools: 14,
    universities: 3,
    offices: 210,
    avgRentVndPerM2: 620_000,
    developmentZone: true,
    visitorIndex: 45,
    marketMaturity: 0.85,
    areaKm2: 12.3,
    nearestMetro: { line: 'Tuyến 3', station: 'Cầu Giấy', distanceM: 450 },
  },
  {
    slug: 'ha-dong',
    name: 'Hà Đông',
    cluster: 'Văn Quán – Mỗ Lao residential towers',
    center: [105.77, 20.96],
    population: 380_000,
    incomeIndex: 58,
    officeWorkersK: 24,
    studentsK: 30,
    footTrafficIndex: 72,
    metroAccessibility: 76,
    metroLines: 1,
    schools: 20,
    universities: 1,
    offices: 90,
    avgRentVndPerM2: 430_000,
    developmentZone: true,
    visitorIndex: 32,
    marketMaturity: 0.45,
    areaKm2: 49.6,
    nearestMetro: { line: 'Tuyến 2A', station: 'Văn Quán', distanceM: 600 },
  },
  {
    slug: 'tay-ho',
    name: 'Tây Hồ',
    cluster: 'Xuân Diệu – Quảng An lakeside',
    center: [105.823, 21.07],
    population: 160_000,
    incomeIndex: 88,
    officeWorkersK: 20,
    studentsK: 10,
    footTrafficIndex: 76,
    metroAccessibility: 48,
    metroLines: 0,
    schools: 9,
    universities: 0,
    offices: 70,
    avgRentVndPerM2: 900_000,
    developmentZone: false,
    visitorIndex: 90,
    marketMaturity: 0.6,
    areaKm2: 24.4,
    nearestMetro: null,
  },
  {
    slug: 'hoan-kiem',
    name: 'Hoàn Kiếm',
    cluster: 'Old Quarter – Hồ Gươm core',
    center: [105.8542, 21.0285],
    population: 150_000,
    incomeIndex: 82,
    officeWorkersK: 46,
    studentsK: 8,
    footTrafficIndex: 98,
    metroAccessibility: 70,
    metroLines: 0,
    schools: 8,
    universities: 0,
    offices: 180,
    avgRentVndPerM2: 950_000,
    developmentZone: false,
    visitorIndex: 96,
    marketMaturity: 1.0,
    areaKm2: 5.3,
    nearestMetro: null,
  },
  {
    slug: 'dong-da',
    name: 'Đống Đa',
    cluster: 'Thái Hà – Chùa Bộc university belt',
    center: [105.8285, 21.0175],
    population: 370_000,
    incomeIndex: 62,
    officeWorkersK: 34,
    studentsK: 62,
    footTrafficIndex: 85,
    metroAccessibility: 70,
    metroLines: 1,
    schools: 22,
    universities: 5,
    offices: 120,
    avgRentVndPerM2: 480_000,
    developmentZone: false,
    visitorIndex: 48,
    marketMaturity: 0.9,
    areaKm2: 9.96,
    nearestMetro: { line: 'Tuyến 2A', station: 'Thái Hà', distanceM: 380 },
  },
  {
    slug: 'thanh-xuan',
    name: 'Thanh Xuân',
    cluster: 'Nguyễn Trãi – Royal City corridor',
    center: [105.81, 20.993],
    population: 290_000,
    incomeIndex: 64,
    officeWorkersK: 30,
    studentsK: 40,
    footTrafficIndex: 78,
    metroAccessibility: 82,
    metroLines: 1,
    schools: 16,
    universities: 2,
    offices: 95,
    avgRentVndPerM2: 380_000,
    developmentZone: false,
    visitorIndex: 40,
    marketMaturity: 0.75,
    areaKm2: 9.1,
    nearestMetro: { line: 'Tuyến 2A', station: 'Thượng Đình', distanceM: 520 },
  },
  {
    slug: 'hai-ba-trung',
    name: 'Hai Bà Trưng',
    cluster: 'Bà Triệu – Times City',
    center: [105.858, 21.008],
    population: 310_000,
    incomeIndex: 68,
    officeWorkersK: 38,
    studentsK: 20,
    footTrafficIndex: 80,
    metroAccessibility: 58,
    metroLines: 0,
    schools: 18,
    universities: 2,
    offices: 140,
    avgRentVndPerM2: 500_000,
    developmentZone: false,
    visitorIndex: 55,
    marketMaturity: 0.85,
    areaKm2: 10.1,
    nearestMetro: null,
  },
  {
    slug: 'gia-lam',
    name: 'Gia Lâm',
    cluster: 'Trâu Quỳ – Vinhomes Ocean Park',
    center: [105.96, 21.02],
    population: 300_000,
    incomeIndex: 52,
    officeWorkersK: 10,
    studentsK: 14,
    footTrafficIndex: 52,
    metroAccessibility: 30,
    metroLines: 0,
    schools: 15,
    universities: 1,
    offices: 35,
    avgRentVndPerM2: 240_000,
    developmentZone: true,
    visitorIndex: 34,
    marketMaturity: 0.35,
    areaKm2: 114,
    nearestMetro: null,
  },
  {
    slug: 'long-bien',
    name: 'Long Biên',
    cluster: 'Aeon Mall – Vinhomes Riverside',
    center: [105.89, 21.045],
    population: 300_000,
    incomeIndex: 60,
    officeWorkersK: 18,
    studentsK: 16,
    footTrafficIndex: 66,
    metroAccessibility: 40,
    metroLines: 0,
    schools: 17,
    universities: 0,
    offices: 60,
    avgRentVndPerM2: 300_000,
    developmentZone: true,
    visitorIndex: 46,
    marketMaturity: 0.5,
    areaKm2: 60,
    nearestMetro: null,
  },
  {
    slug: 'nam-tu-liem',
    name: 'Nam Từ Liêm',
    cluster: 'Mỹ Đình – Keangnam business area',
    center: [105.765, 21.013],
    population: 265_000,
    incomeIndex: 70,
    officeWorkersK: 40,
    studentsK: 18,
    footTrafficIndex: 74,
    metroAccessibility: 62,
    metroLines: 0,
    schools: 13,
    universities: 1,
    offices: 150,
    avgRentVndPerM2: 420_000,
    developmentZone: true,
    visitorIndex: 52,
    marketMaturity: 0.6,
    areaKm2: 32,
    nearestMetro: null,
  },
];

const CATEGORY_BY_KEY = new Map(CATEGORIES.map((c) => [c.key, c]));
const LOCATION_BY_SLUG = new Map(LOCATIONS.map((l) => [l.slug, l]));

const DEMO_NOTE =
  'Toàn bộ số liệu (dân số, thu nhập, giá thuê, đối thủ, lưu lượng khách...) là dữ liệu DEMO/ƯỚC TÍNH cho bản MVP — ' +
  'không phải số liệu thị trường chính thức.';

module.exports = { CATEGORIES, LOCATIONS, CATEGORY_BY_KEY, LOCATION_BY_SLUG, DEMO_NOTE };
